# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pulp}
  s.version = "0.0.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mh"]
  s.date = %q{2012-09-15}
  s.description = %q{A little ruby wrapper around the pulp (http://pulpproject.org) API}
  s.email = %q{mh@immerda.ch}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/repositories.rb",
    "examples/test_pulp.yml",
    "lib/pulp.rb",
    "lib/pulp/cds.rb",
    "lib/pulp/common/debug.rb",
    "lib/pulp/common/lifecycle.rb",
    "lib/pulp/common/lifecycle/create.rb",
    "lib/pulp/common/lifecycle/delete.rb",
    "lib/pulp/common/lifecycle/get.rb",
    "lib/pulp/common/lifecycle/update.rb",
    "lib/pulp/connection/base.rb",
    "lib/pulp/connection/handler.rb",
    "lib/pulp/consumer.rb",
    "lib/pulp/consumergroup.rb",
    "lib/pulp/content.rb",
    "lib/pulp/distribution.rb",
    "lib/pulp/errata.rb",
    "lib/pulp/event.rb",
    "lib/pulp/filter.rb",
    "lib/pulp/package.rb",
    "lib/pulp/package_group.rb",
    "lib/pulp/package_group_category.rb",
    "lib/pulp/repository.rb",
    "lib/pulp/service.rb",
    "lib/pulp/task.rb",
    "lib/pulp/task_history.rb",
    "lib/pulp/task_snapshot.rb",
    "lib/pulp/user.rb",
    "pulp.gemspec",
    "spec/pulp/common/debug_spec.rb",
    "spec/pulp/common/lifecycle/create_spec.rb",
    "spec/pulp/common/lifecycle/delete_spec.rb",
    "spec/pulp/common/lifecycle/get_spec.rb",
    "spec/pulp/common/lifecycle/update_spec.rb",
    "spec/pulp/common/lifecycle_spec.rb",
    "spec/pulp/connection/base_spec.rb",
    "spec/pulp/connection/handler_spec.rb",
    "spec/pulp/content_spec.rb",
    "spec/pulp/package_spec.rb",
    "spec/pulp/repository_spec.rb",
    "spec/pulp/service_spec.rb",
    "spec/pulp/task_spec.rb",
    "spec/pulp_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{https://github.com/duritong/ruby-pulp}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{A little ruby wrapper around the pulp API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, ["~> 1.6.7"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

